name: Validate Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

permissions: read-all

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - name: Run checkov
        uses: bridgecrewio/checkov-action@1246d92f57abae29d5db5f9aeeed2a9813e52d7d  # v12
        id: checkov
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
          var_file: test/dummy-vars.yaml
        env:
          HELM_NAMESPACE: dummy-ns
        continue-on-error: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd  # v4
        with:
          sarif_file: results.sarif

      - name: Report failure
        if: steps.checkov.outcome == 'failure'
        run: |
          echo "The checkov scan resulted in failure. See the output of the above step."
          exit 1
